### ISSUE TITLE
Add TypeScript support to the project

### ISSUE THREAD

**Issue by vrann** [magento-engcom/community-portal#1]
For the Community Portal project start using typescript for all the generated code.
 Typescript should compiled to ES6 during the packaging of the serverless functions

https://github.com/StefH/serverless-aws-lambda-typescript-examples/tree/master/serverless-aws-lambda-typescript-webpack
https://www.jamestharpe.com/serverless-typescript-getting-started/

**Comment by XiyaMagento** [comment]
I tried changing /functions/webpack.config.js to /functions/webpack.config.ts but that makes it not possible to run the command <serverless webpack> properly

If we want to use the serverless webpack command for e.g. serverless webpack --out dist, then we need to keep the webpack.config.js JavaScript file
