### ISSUE TITLE
Add Margins for the sidebar button

### ISSUE THREAD

**Issue by vrann** [magento-engcom/community-portal#126]
Sidebar button should have equal indentation to left and right:
![Screen Shot 2018-07-12 at 4.33.25 PM.png](https://images.zenhubusercontent.com/579b6ed3e40e5714b16cb3d3/49b3636d-53ed-4e6f-b011-d82a99555b72)

**Comment by athensbird** [comment]
When the window is shrank to a small size, the side margins look really weird. Should I add the right margin for large-size windows, while removing/shrinking margins for small viewpoints?
