### ISSUE TITLE
Contributor Profile

### ISSUE THREAD

**Issue by vrann** [magento-engcom/community-portal#13]
As a Contributor, I' like to see my profile so that I can track my activities and statistic

AC:
For logged in user
- it should be possible to see the list of bookmarked/subscribed projects
- it is possible to see the list of the projects he pledged hours to
- should be able to edit and display profile information
  - name
  - company
  - description

**Comment by magento-engcom-team** [comment]
Issue is moved to https://github.com/magento/engcom-community-portal/issues/30
