### ISSUE TITLE
Github Synchronization. Project Stat

### ISSUE THREAD

**Issue by vrann** [magento-engcom/community-portal#14]
As a Magento employee and community member I'd like to track the projects activity and see statistic on contributors and their actions

AC:
- it should be possible to see the number of joined and pledged users
- it should be possible to see the number of the meetings happened and links to recordings
- it should be possible to see the number of contributors to the repository and rank top contributors
- it should be possible to see the burndown chart for the project

**Comment by magento-engcom-team** [comment]
Issue is moved to https://github.com/magento/engcom-community-portal/issues/29
