### ISSUE TITLE
Contributing Partners self-management console

### ISSUE THREAD

**Issue by ishakhsuvarov** [magento-engcom/community-portal#16]
To simplify program participation for Contributing Partners additional automated flows must be introduced to the process.

**AC:**
1. Community Engineering representative can create Partner Teams assigning team name and Technical Lead account for the team. (magento-engcom/community-portal#17)
2. Team's technical lead is capable of logging into the system with the Github account and manage other Github accounts on the Partner Team (add / remove / modify members, view members status in 2FA and organizations participation, view teams achievements with breakdown by periods and members, etc). (magento-engcom/community-portal#15)
3. Partner Contributors may see their and their teams standing and all of the relevant information. (magento-engcom/community-portal#18)

**Comment by magento-engcom-team** [comment]
Issue is moved to https://github.com/magento/engcom-community-portal/issues/28
