### ISSUE TITLE
Adapt Pledge Functionality

### ISSUE THREAD

**Issue by XiyaMagento** [magento-engcom/community-portal#209]
- replace ‘pledge’ functionality with something simpler like ‘count on me’ with no hours
- when user clicks on the pledge button, a pop-up would be open with text describing the responsibilities and commitments of pledgers, and a 'count on me' button to formally pledge the project

**Comment by athensbird** [comment]
Since we don't know the hours pledgers are willing to put in, are we removing the circular progress on the card as well? Or replace the hours with a pledger-based count (e.g., 3/7 pledgers needed)?
