### ISSUE TITLE
Display User Contribution Statistics with Charts

### ISSUE THREAD

**Issue by athensbird** [magento-engcom/community-portal#214]
1. For each user, display his total contributions (PR/commits) in an appropriate chart(line chart/stacked column chart) grouped by different projects he is a part of.

2. For each project, 
   1. display the total contribution data visually (e.g., created/accepted PRs) grouped by time periods (week/month/quarter/year) in an appropriate chart format
   2. display the project progress by showing a burndown chart

3. Design the database schema for the functionalities above

4. Load sample test data into database

5. Create API endpoints for step 1) and 2)

6. Set up front- and back-end testing suites

AC:

1. For every project, the card should display latest statistics and charts that contains #PR grouped by time periods
2. For every user, his profile page should display latest statistics and charts that contains #PR grouped by time periods

Consider using D3.js/HighChart.js

Use the portal's stats as a reference
http://engcom.corp.magento.com/pull-request-statistic?period=latest&r[]=magento-engcom/php-7.2-support#open-vs-processed-year

**Comment by athensbird** [comment]
![Screen Shot 2018-08-03 at 5.42.06 PM.png](https://images.zenhubusercontent.com/5b0d8aed4ee89f4a5e0d8166/3b07d960-020b-4098-b419-1f7335dfa77e)

Here is what I have for now - basically a line chart displaying the #PR for the user over time. Plan to add a project filter and dynamic timeline selection (expand available units to weeks, years, etc)

**Comment by magento-engcom-team** [comment]
Issue is moved to https://github.com/magento/engcom-community-portal/issues/23
