### ISSUE TITLE
Miscellaneous Front-end Issues

### ISSUE THREAD

**Issue by XiyaMagento** [magento-engcom/community-portal#232]
- Remove margin surrounding body:

![image.png](https://images.zenhubusercontent.com/5b0d896b4ee89f4a5e0d8162/af6f3de2-640d-4b1a-9977-42abbaff8db4)

- The headbar in the auth page should only contain login logo without sidebar icon or login

- Add margin space between the hamburger and the logo

- Rename 'pledger' to 'join'

- Hide editButton while not implemented

- On ProjectCard, align Git, Slack and Edit Button

**Comment by athensbird** [comment]
For the first point, should we consider making the sidebar/login as separate components and import them to headbar? Could you please clarify? @vrann
