### ISSUE TITLE
Contributors Statistic Page

### ISSUE THREAD

**Issue by VladimirZaets** [magento-engcom/community-portal#335]
Same as on magento.com but with the full list of contributors and additional filters.

Show full list of the contributors with filters:
	* Per month
	* Per year
        * Quater
	* Per project
	* Created
	* Merged
	* Closed

We should have ability to any mix of this filters.

**Comment by magento-engcom-team** [comment]
Issue is moved to https://github.com/magento/engcom-community-portal/issues/12
