### ISSUE TITLE
Configure restrictive policies on the AWS Lambda

### ISSUE THREAD

**Issue by vrann** [magento-engcom/community-portal#6]
Restrict access fro AWS Lamdas deployed with AWS to the most restrictive permissions in serverless.yaml

**Comment by athensbird** [comment]
Should we limit the access to certain users/roles or just setup an authentication mechanism to invoke the Lambda functions? Also, should we customize policies for each Lambda function, or just come up with a universal policy that applies to all the Lambdas?
