### ISSUE TITLE
Fix the async token problem when getting the liked projects

### ISSUE THREAD

**Issue by XiyaMagento** [magento-engcom/community-portal#96]
- Fix the problem of "getting the list of liked projects occurs before the user token is stored"

**Comment by athensbird** [comment]
Shouldn't it be the other way around? Like the token is saved first and with that redux loads the likedProjects? The likedProject array is empty before the token could be retrieved. 

I believe this issue has already been fixed yesterday. Please let me know if you've encountered any issues. @XiyaMagento

**Comment by XiyaMagento** [comment]
Yes. I meant "getting the list of liked projects occurs before the user token is stored" is the problem to be fixed. My bad it's not clear. Feel free to move this issue to the QA/Review section if it's fixed :)
